### ISSUE TITLE
controller-state should match against MediaRenderer:1 or greater

### ISSUE THREAD

**Issue by ali1234** [hzeller/upnp-display#1]
https://github.com/hzeller/upnp-display/blob/master/controller-state.cc#L27

For compatibility this should test for ""urn:schemas-upnp-org:device:MediaRenderer:" followed by any number equal or greater than 1. UPnP spec requires backwards compatibility for renderers which report a greater number.

**Comment by hzeller** [comment]
Cool, can you send a pull request that does a prefix compare with strncmp() ?
